image: atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build
        script:
          - zip -r myapp.zip app
        artifacts:
          - myapp.zip

    - step:
        name: Upload to S3
        services:
          - docker
        script:
          # Test upload
          - pipe: atlassian/aws-code-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
              AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
              AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
              COMMAND: 'upload'
              APPLICATION_NAME: 'ggatus-usages'
              ZIP_FILE: 'myapp.zip'

    - step:
        name: Deploy with CodeDeploy
        services:
        - docker
        script:
        # Test upload
        - pipe: atlassian/aws-code-deploy:0.2.3
          variables:
            AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
            AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
            COMMAND: 'deploy'
            APPLICATION_NAME: 'ggatus-usages'
            DEPLOYMENT_GROUP: 'ggatus-usages-group'
            IGNORE_APPLICATION_STOP_FAILURES: 'true'
            FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
            WAIT: 'true'


