# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: app/package-lock.json
    - run: npm install -g mocha
    - run: npm install
    - name: zip creation
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: 'app.zip'
        directory: app/
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - run: ls
    - run: pwd
    - name: 'Task 1: Connect to AWS '
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: 'Task 2: Upload  to S3 bucket'
      run: aws s3 cp app.zip s3://githubaction-nodejs-app
#   test:
#      needs: build
#      runs-on: ubuntu-latest
#      steps:
#      - name: 'Testing '
#      - run : echo 'testing'
#      - run : npm run test
  deploy: 
     needs: build
     runs-on: ubuntu-latest
     steps:
#      - name: Install AWS CLI 2
#        run: |
#           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#           unzip awscliv2.zip
#           sudo ./aws/instal
          
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
     - name: Deploy to AWS
       run: 
         aws deploy create-deployment --application-name github-nodejs-app --deployment-group-name DG1 --s3-location bucket=githubaction-nodejs-app,key=app.zip,bundleType=zip
 
